### ISSUE TITLE
Editors cannot create new filemounts

### ISSUE THREAD

**Issue by christianbltr** [bmoex/my_user_management#11]
As an editor I want to create a new filemount.

After clicking on the "create new" icon I get the following error:

#1437745221: Not implemented. User 2 creats new record sys_filemounts on root node.

The function works for admin users.

Tested on TYPO3 7.6.2, my_user_management 2.2.0

**Comment by christianbltr** [comment]
As far as I can see in 

https://github.com/TYPO3/TYPO3.CMS/blame/master/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseUserPermissionCheck.php#L107

the permission check has been changed when the new backend form engine has been implemented. 
The question is: Is there any chance to give editors the possibility to create new records on root page now?

**Comment by bmoex** [comment]
https://forge.typo3.org/issues/75147

**Comment by bmoex** [comment]
The fix has just been merged in the core. Will be fixed in next 7.6.5 release and future releases (8.x).
