### ISSUE TITLE
Login History module does not work

### ISSUE THREAD

**Issue by christianbltr** [bmoex/my_user_management#12]
As an editor (applies also to admin users) I want to access the Login History.

#1289386765: Could not analyse class: "TYPO3\CMS\Beuser\ViewHelpers\SpriteManagerIconViewHelper" maybe not loaded or no autoloader?

Tested on TYPO3 7.6.2, my_user_management 2.2.0

**Comment by bmoex** [comment]
Fixed by https://github.com/bmoex/my_user_management/commit/058b5143ce299e715e54d8d483277f30e554222a
