### ISSUE TITLE
Fatal error: Call to a member function getDocHeaderComponent()

### ISSUE THREAD

**Issue by dp-michaelhuebe** [bmoex/my_user_management#5]
I got these error message when i use "User Admin" Module on TYPO3 CMS 7.6.1:

Fatal error: Call to a member function getDocHeaderComponent() on null in /var/www/htdocs/typo3_src/typo3/sysext/beuser/Classes/Controller/BackendUserActionController.php on line 93

![my-user-management-error-1](https://cloud.githubusercontent.com/assets/5189184/11894573/6128c5c4-a578-11e5-82b6-82c6a8e4009c.png)

**Comment by christianbltr** [comment]
I can confirm this on a 7.6.2 system.

**Comment by johannessteu** [comment]
Same problem for me!

**Comment by johannessteu** [comment]
This is fixed with 2.1.2
