### ISSUE TITLE
Edit file mounts shows a blank page

### ISSUE THREAD

**Issue by johannessteu** [bmoex/my_user_management#6]
On 7.6.2 the edit file mounts action display a white page instead of the form

**Comment by johannessteu** [comment]
Still the same error with TYPO3 7.7.3 and my_user_management 2.1.2

**Comment by bmoex** [comment]
Sorry for the late reply, didn't receive any email about new issues. Will handle all issues asap.

**Comment by bmoex** [comment]
There is a [core bug](https://forge.typo3.org/issues/75147) on creation. The edit seems to work correctly on my machine. Can you put a screencast please? Is this still applicable?

**Comment by johannessteu** [comment]
The error still exists with TYPO3 7.6.4 and my_user_management 2.2.1. I'm sorry, can't hand in a screencast. but the center frame will just be a blank page as soon as you click on edit or add button
![screen shot 2016-03-17 at 08 46 29](https://cloud.githubusercontent.com/assets/769789/13839631/c6693cd0-ec1c-11e5-996e-639019b3f914.png)

**Comment by bmoex** [comment]
Hi,

A white screen normally means a PHP error. Is there something in the error log that can point me in the right direction?

Kind regards,

**Comment by johannessteu** [comment]
Hi,  guess it's just the core bug! The white page was cause of a miss configuration for that user. He wasn't allowed to modify filemoints. On creation there is now a `#1437745221: Not implemented. User 79 creats new record sys_filemounts on root node `

**Comment by bmoex** [comment]
Ok, will wait till the corebug is resolved and merged. Thanks for reporting!

**Comment by bmoex** [comment]
The fix has just been merged in the core. Will be fixed in next 7.6.5 release and future releases (8.x).
